# ACCTON CSP9550 Platform modules

ACCTON_CSP9550_PLATFORM_MODULE_VERSION = 1.1

export ACCTON_CSP9550_PLATFORM_MODULE_VERSION

ACCTON_CSP9550_PLATFORM_MODULE = sonic-platform-modules-accton-csp9550_$(ACCTON_CSP9550_PLATFORM_MODULE_VERSION)_amd64.deb
$(ACCTON_CSP9550_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-accton-csp9550
$(ACCTON_CSP9550_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ACCTON_CSP9550_PLATFORM_MODULE)_PLATFORM = x86_64-accton_csp9550-r0
SONIC_DPKG_DEBS += $(ACCTON_CSP9550_PLATFORM_MODULE)

SONIC_STRETCH_DEBS += $(ACCTON_CSP9550_PLATFORM_MODULE)