# Accton csp7551 Platform modules

ACCTON_CSP7551_PLATFORM_MODULE_VERSION = 1.1

export ACCTON_CSP7551_PLATFORM_MODULE_VERSION

ACCTON_CSP7551_PLATFORM_MODULE = sonic-platform-modules-accton-csp7551_$(ACCTON_CSP7551_PLATFORM_MODULE_VERSION)_amd64.deb
$(ACCTON_CSP7551_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-accton
$(ACCTON_CSP7551_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ACCTON_CSP7551_PLATFORM_MODULE)_PLATFORM = x86_64-accton_csp7551-r0
SONIC_DPKG_DEBS += $(ACCTON_CSP7551_PLATFORM_MODULE)